# Generated by Django 2.2.6 on 2019-10-24 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='a_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='a_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='a_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='a_title',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='a_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
