# Generated by Django 2.2.6 on 2019-10-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191024_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='a_title',
            field=models.TextField(max_length=255),
        ),
    ]
