# Generated by Django 2.2.6 on 2019-10-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191024_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='a_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_updated',
            new_name='updated',
        ),
    ]
