# Generated by Django 2.2.6 on 2019-10-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191024_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_at',
            new_name='created',
        ),
    ]
